Branch/save
ITA-Dnipro/Sf-073.Java-3 pull request #41
Opened 2022-12-23 17:23 UTC by Martin0071

Added save functionality

2022-12-24 07:19 UTC, penzata requested changes
Please, consider all the comments.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImplTest.java
> +package org.example.persistence.ormanager;
It is best all the test files to be in the test directory.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManager.java
> +    Student save(Student student);
Wouldn't it be better to use generics for the CRUD methods in the interface.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +        Connection connection;
We are going to use connection and statement in all of our methods. Maybe consider making them fields.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +        try {
Maybe try using try-with-resources here for the connection and the statement.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +        return student;
As of this, we are returning the same object (with null Id state) that was passed in the method initially without any change.
Consider getting the auto-generated ID for this object from the database, set it, and then return the complete object.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +            statement.execute("CREATE TABLE IF NOT EXISTS STUDENTS (first_name VARCHAR(255)) ;");
About this row and two rows below (row 39): it is always considered good practice to make the sql statements (or the most often used ones) constants and pass a constant in the methods, not the whole string itself.

And about the table creation: right now you are creating a table with just one column. Try checking out the table schema file in the resources directory.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +            System.out.println(rows + " rows affected.");
Please, don't commit any System.out print lines. If you want to see your current result use Logger for debugging.

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +            throw new RuntimeException(e);
Consider handling the exception, not throwing a new one.
Here's a good information about handling that you can use: https://docs.oracle.com/javase/tutorial/jdbc/basics/sqlexception.html

2022-12-24 07:19 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +public class ORManagerImpl implements org.example.persistence.ormanager.ORManager {
Why using the whole name of the ORManager interface?

2022-12-25 12:58 UTC, veselin-petkov approved these changes

2022-12-25 13:03 UTC, penzata approved these changes

2022-12-25 13:18 UTC, merged