Many to One relationship added to Student
ITA-Dnipro/Sf-073.Java-3 pull request #68
Opened 2022-12-29 22:06 UTC by veselin-petkov

2022-12-30 05:16 UTC, Martin0071 approved these changes

2022-12-30 08:47 UTC, penzata requested changes
I know that the comments' contents are a lot but please consider them.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/domain/model/SchoolClass.java
> +public class SchoolClass {
Please remove "class" tautology from SchoolClass, school_class, etc.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/persistence/ormanager/ORManagerImpl.java
> +                System.out.println(sqlCreateTable);
Please, do not commit system.out.print, especially when you have logger below.

The log folder is in the main directory, from there you can examine the file with the current logs. Or you can use the logger from the tests folder which prints to the console if it is more convenient to you.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/persistence/utilities/AnnotationUtils.java
> +            if (declaredField.isAnnotationPresent(Column.class)) {
Don't need this if check. This is done in the getColumnName() itself.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/persistence/utilities/AnnotationUtils.java
> +                columnNames.add("FOREIGN KEY(" + columnName + ") REFERENCES " + referenceTableName + "(id)");
Right now, you are adding the foreign key in the beginning of the table. Don't you need to add it at the end of the sql statement?

We don't have a row for the School in the switch-case for the creation of the table. We can unite it long, something like this: case "Long", "long", "School" -> columnNames.add(columnName + SQLDialect.LONG + constraints);

getColumnName() return either the name of the column or if the annotation Column is absent the name of the field, in our case - schoolClass, which can be rewritten to schoolId. The getColumnNameFromManyToOne() is redundant.

Because right now this columnNames.add("FOREIGN KEY(" + columnName + ") REFERENCES " + referenceTableName + "(id)") will provide this: "FOREIGN KEY(school_class_id) REFERENCES school_class(id)" but we don't have the "school_class_id" column creation in students table.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/persistence/utilities/AnnotationUtils.java
> +                fieldName = "Long";
Why are you hardcoding the fieldName? This way you will get wrong result.
In this case, fieldName should be SchoolClass which it is, not Long.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/persistence/utilities/AnnotationUtils.java
> +            String idTag = "";
Those 4 rows above are useless. When you need to change the value for any of it for ManyToOne just assign it to the variable then.

2022-12-30 08:47 UTC, penzata commented on src/main/java/org/example/persistence/utilities/AnnotationUtils.java
> +            return fieldName.equals("") ? field.getName() : fieldName;
Consider this: in one case you will get return value "schoolClass", in the other case you will get "school_class_id".

2023-01-04 16:15 UTC, penzata approved these changes

2023-01-04 16:34 UTC, merged